# Generated by Django 5.1.1 on 2024-10-10 06:49

import Utils.models.Methods
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Name is Used ,it must be Unique'}, max_length=50, unique=True, verbose_name='Name')),
                ('translations', models.JSONField(blank=True, null=True, verbose_name='Translations')),
            ],
            options={
                'verbose_name': 'Organization Type',
                'verbose_name_plural': 'Organizations Types',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Name is Used ,it must be Unique'}, max_length=50, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=Utils.models.Methods.upload_image_to, verbose_name='Logo')),
                ('translations', models.JSONField(blank=True, null=True, verbose_name='Translations')),
                ('email', models.EmailField(error_messages={'unique': 'E-Mail must Unique'}, max_length=254, unique=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'UniversityType',
                'verbose_name_plural': 'University Types',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Name is Used ,it must be Unique'}, max_length=50, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=Utils.models.Methods.upload_image_to, verbose_name='Logo')),
                ('translations', models.JSONField(blank=True, null=True, verbose_name='Translations')),
                ('affiliated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Organizations', to='Organization.organization', verbose_name='Affiliated To')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organizations', to='Organization.organizationtype', verbose_name='Organization Type')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organizations', to='Organization.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Name is Used ,it must be Unique'}, max_length=50, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=Utils.models.Methods.upload_image_to, verbose_name='Logo')),
                ('translations', models.JSONField(blank=True, null=True, verbose_name='Translations')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Colleges', to='Organization.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
            },
        ),
    ]
