# Generated by Django 5.1.1 on 2024-10-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Name is Used ,it must be Unique'}, max_length=50, unique=True, verbose_name='Name')),
                ('translations', models.JSONField(blank=True, null=True, verbose_name='Translations')),
                ('iso_code', models.CharField(max_length=5, unique=True, verbose_name='ISO Code')),
                ('symbol', models.CharField(blank=True, max_length=5, null=True, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s+', to='Currency.currency', verbose_name='Currency')),
                ('exchange_2_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s+', to='Currency.currency', verbose_name='Exchange to Currency')),
            ],
            options={
                'verbose_name': 'Currency Exchange Rate',
                'verbose_name_plural': 'Currencies Exchange Rates',
                'unique_together': {('currency', 'exchange_2_currency')},
            },
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rates',
            field=models.ManyToManyField(through='Currency.CurrencyExchangeRate', to='Currency.currency', verbose_name='Exchange Rates'),
        ),
    ]
