# Generated by Django 5.1.1 on 2024-10-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Name is Used ,it must be Unique'}, max_length=50, unique=True, verbose_name='Name')),
                ('translations', models.JSONField(blank=True, null=True, verbose_name='Translations')),
                ('payment_Method_type', models.CharField(choices=[('M', 'Monetary'), ('Cr', 'Credit Card'), ('BT', 'Bank Transfer'), ('Ch', 'Check'), ('MT', 'Money Transfer'), ('MC', 'Mobile Cach')], default='M', max_length=2, verbose_name='Payment Method Type')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Name is Used ,it must be Unique'}, max_length=50, unique=True, verbose_name='Name')),
                ('translations', models.JSONField(blank=True, null=True, verbose_name='Translations')),
                ('payment_status_type', models.CharField(choices=[('P', 'Paid'), ('L', 'Pay later'), ('PP', 'Partially Paid')], default='P', max_length=2, verbose_name='Payment Status Type')),
            ],
            options={
                'verbose_name': 'PaymentStatus',
                'verbose_name_plural': 'Payment Statuses',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('notified_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Notified Days')),
                ('reference_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Reference Number')),
                ('bank_deposit_date', models.DateTimeField(blank=True, null=True, verbose_name='Bank Deposit Date')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('total_required_amount', models.FloatField(verbose_name='Total Required Amount')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='Currency.currency', verbose_name='Currency')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='Payment.paymentmethod', verbose_name='Payment Method')),
                ('payment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='Payment.paymentstatus', verbose_name='Payment Status')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
