# Generated by Django 5.1.1 on 2024-10-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment', '0001_initial'),
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='Reservation.reservation', verbose_name='Reservation'),
        ),
    ]
