# Generated by Django 5.1.1 on 2024-10-10 06:49

import Utils.models.Methods
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAlbum',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Utils.models.Methods.upload_image_to, verbose_name='Photo')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Event Album',
                'verbose_name_plural': 'Events Albums',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Name is Used ,it must be Unique'}, max_length=50, unique=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Utils.models.Methods.upload_image_to, verbose_name='Image')),
                ('translations', models.JSONField(blank=True, null=True, verbose_name='Translations')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Utils.models.Methods.upload_image_to, verbose_name='Image')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('hall', models.CharField(max_length=100, verbose_name='Hall')),
                ('lecturer_financial_dues', models.FloatField(blank=True, null=True, verbose_name='Lecturer Financial Dues')),
                ('lecturer_financial_system', models.CharField(choices=[('A', 'All Event'), ('E', 'Each Student'), ('N', 'Enlist')], default='N', max_length=100, verbose_name='Hall')),
                ('event_paid_status', models.CharField(choices=[('F', 'Completely '), ('P', 'Partially Paid'), ('C', 'Completely Paid')], default='F', max_length=100, verbose_name='Event Paid Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Date Time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='Category.category', verbose_name='Category')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='Organization.college', verbose_name='College')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
