"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from os.path import join, exists, dirname  # noqa: F401
import django
from django.urls import reverse_lazy  # noqa: F401
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ASSETS_DIR = join(BASE_DIR, "Assets")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-51v+!c+^ay(#p^)i#r5vg#00us2c@$2^7@frouj!n94j&-s%k="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

AUTH_USER_MODEL = "User.User"

# # for Access User Profile example(profile = request.user.get_profile())
AUTH_PROFILE_MODEL = "User.Profile"

ALLOWED_HOSTS = [
    "*",
    "localhost",
    "127.0.0.1",
    "herokuapp.com",
]

APPEND_SLASH = True

## Application definition

# 3rd Libraries
THIRD_LIBRARIES = [
    "polymorphic_tree",
    "polymorphic",
    "mptt",
    "rest_framework",  # Django rest framework (drf)
    "rest_framework.authtoken",  # Adding token based authentication from drf
    "django_filters",
    # "corsheaders",
    # the debug toolbar
    "debug_toolbar",
]

# My Applications
MY_APPS = [
    "Utils",
    "Locale",
    "Currency",
    "Address",
    "Category",
    "Organization",
    "User",
    "Event",
    "Reservation",
    "Payment",
    "Advertisement",
    "Notification",
    "Favorite",
    ##
    # "Logs",
    ##
    # "FireBase",
    ## Api RestFrameWork & GraphQL
    "Api",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # NEW
    ## 3rd Libraraies
    *THIRD_LIBRARIES,
    ## My Apps
    *MY_APPS,
    "django.forms",
]

SITE_ID = 2

USE_HTTPS = False

INTERNAL_IPS = [
    # ...
    "127.0.0.1",  # Add your development machine's IP address here
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # for corsheaders
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # for Multi Languages & Translation
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # debug toolbar middleware
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "Locale.middleware.userLanguage.UserLanguageMiddleware",  # Custom Middleware for App Locale
]

ROOT_URLCONF = "Config.urls"

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

TEMPLATE_DIR = join(BASE_DIR, "templates")  # ROOT dir for templates

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            TEMPLATE_DIR,
            django.__path__[0] + "/forms/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.i18n",  # for Multi Languages & Translation
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "Database/db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-US"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


PHONENUMBER_DEFAULT_REGION = "EG"

# Supported Languages
LANGUAGES = [
    ("en-US", _("English")),
    ("ar-AS", _("Arabic")),
    ("ar-EG", _("Arabic")),
    ("fr-FR", _("French")),
    ("tr-TR", _("Turkish")),
]

# True for right-to-left languages like Arabic, and to False otherwise
# LANGUAGE_BIDI = False
# Languages using BiDi (right-to-left) layout
LANGUAGES_BIDI = [
    "ar-AS",
    "ar-EG",
    # "he", "ar-dz", "fa", "ur"
]

LOCALE_PATHS = [
    join(ASSETS_DIR, "Locales"),
    # "/home/www/project/common_files/locale",
    # "/var/local/translations/locale",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = join(ASSETS_DIR, "staticfiles")

STATICFILES_DIRS = (join(ASSETS_DIR, "static"),)

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.DefaultStorageFinder",
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"

MEDIA_ROOT = join(ASSETS_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

####
ADMINS = (("Shady", "shadyelnady@gmail.com"),)

MANAGERS = ADMINS

EXTERNAL_USER = "Shady"

## Currency
CURRENCIES = (
    "USD",
    "EUR",
)
CURRENCY_CHOICES = [
    ("USD", "USD $"),
    ("EUR", "EUR €"),
]

DEFAULT_CURRENCY = "EG"

##
# LOGIN_URL = reverse_lazy("User:Log_In")
# LOGIN_REDIRECT_URL = reverse_lazy("Logs:Home")
# LOGOUT_REDIRECT_URL = reverse_lazy("User:Log_In")
# LOGOUT_URL = reverse_lazy("Logs:LogOut")


# AUTHENTICATION_BACKENDS = ["User.utils.backend.UserBackend"]


## REST_FRAMEWORK
REST_FRAMEWORK = {
    # "DATE_FORMAT": "%d/%m/%Y",
    # Use Django"s standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        # "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly",
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        # "FireBase.utils.authentication.FirebaseAuthentication",  # Custom fireBase Authentiction
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "ORDERING_PARAM": "sorters[0][field]",
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    # "EXCEPTION_HANDLER": "utilities.utils.custom_exception_handler",
    # "EXCEPTION_HANDLER": "API.exceptions.django_error_handler"  ## Excepitions
}

APP_LOCALES = {
    "is_set": False,
    "data": None,
    # "en-US": {
    #     "is_bidi": False,
    #     "code": "en",
    #     "flag": "",
    #     "name": "English",
    #     "native_name": "English",
    # },
    # "ar-EG": {
    #     "is_bidi": True,
    #     "code": "ar",
    #     "flag": "",
    #     "name": "Arabic",
    #     "native_name": "العربيّة",
    # },
}

# Email
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "shadyelnady@gmail.com"
EMAIL_HOST_PASSWORD = "uliycfbtwmqqzdrm"
EMAIL_USE_SSL = False
