# Generated by Django 5.1.1 on 2024-10-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
        ('Locale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Countries', to='Locale.language', verbose_name='language'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cities', to='Address.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Governorates', to='Address.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cities', to='Address.governorate', verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='Address.locality', verbose_name='Locality'),
        ),
        migrations.AddField(
            model_name='state',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Areas', to='Address.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Areas', to='Address.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='street',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Streets', to='Address.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='Address.street', verbose_name='Street'),
        ),
    ]
