# Generated by Django 5.1.1 on 2024-10-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Name is Used ,it must be Unique'}, max_length=50, unique=True, verbose_name='Name')),
                ('native_name', models.CharField(blank=True, error_messages={'unique': 'Native Name is Used ,it must be Unique'}, max_length=20, null=True, unique=True, verbose_name='Native Name')),
                ('language_iso_code', models.CharField(max_length=2, unique=True, verbose_name='Language ISO Code')),
                ('is_bidirectional', models.BooleanField(default=False, verbose_name='is Bidirectional')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('is_app_suport', models.BooleanField(default=True, verbose_name='Is Application Support')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locales', to='Address.country', verbose_name='Country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locales', to='Locale.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Locale',
                'verbose_name_plural': 'Locales',
            },
        ),
    ]
