# Generated by Django 5.1.1 on 2024-10-10 06:49

import User.utils.userRegexValidators
import Utils.models.Methods
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Currency', '0001_initial'),
        ('Locale', '0001_initial'),
        ('Organization', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UID')),
                ('user_type', models.CharField(choices=[('D', 'Developer'), ('SU', 'Super User'), ('A', 'Admin'), ('L', 'Lecturer'), ('St', 'Staff'), ('S', 'Student'), ('U', 'User')], max_length=2, verbose_name='User Type')),
                ('username', models.CharField(error_messages={'unique': 'Name must be Unique'}, max_length=100, unique=True, validators=[User.utils.userRegexValidators.UserRegexValidators.name_regex], verbose_name='User Name')),
                ('email', models.EmailField(error_messages={'unique': 'E-Mail must Unique'}, max_length=254, unique=True, verbose_name='E-mail')),
                ('mobile', models.CharField(error_messages={'unique': 'Mobile must Unique'}, max_length=16, unique=True, validators=[User.utils.userRegexValidators.UserRegexValidators.mobile_regex], verbose_name='Mobile')),
                ('otp', models.CharField(blank=True, max_length=4, null=True, verbose_name='OTP')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='E-mail Verified At')),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Mobile Verified At')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last LogIn')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='is Blocked')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='UserAlbum',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Utils.models.Methods.upload_image_to, verbose_name='Photo')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsersPhotosAlbum', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Album',
                'verbose_name_plural': 'Users Album',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Students', to='Organization.college', verbose_name='College')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Students', to='Organization.university', verbose_name='University')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=Utils.models.Methods.upload_avatar_to, verbose_name='Avatar')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name')),
                ('national_id', models.CharField(blank=True, error_messages={'unique': 'National ID must Unique'}, max_length=14, null=True, unique=True, validators=[User.utils.userRegexValidators.UserRegexValidators.national_id_regex], verbose_name='National ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('title', models.CharField(blank=True, choices=[('D', 'Doctor'), ('E', 'Engineer'), ('P', 'Professor'), ('S', 'Student')], max_length=1, null=True, verbose_name='Title')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'FeMale')], max_length=1, null=True, verbose_name='Gender')),
                ('university_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='University Number')),
                ('is_graduate', models.BooleanField(default=True, verbose_name='is Graduate')),
                ('contact_info', models.JSONField(blank=True, null=True, verbose_name='Contact Info')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Persons', to='Currency.currency', verbose_name='Currency')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Persons', to='Locale.language', verbose_name='Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Lecturers', to='Category.category', verbose_name='Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Lecturer', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Interests', to='Category.category', verbose_name='Category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Interests', to='User.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'unique_together': {('student', 'category')},
            },
        ),
    ]
