# Generated by Django 5.1.1 on 2024-10-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_status', models.CharField(choices=[('I', 'Initialzation Reservation'), ('C', 'Canceled Reservation'), ('R', 'Confirmed Reservation'), ('H', 'Hold Reservation')], default='I', max_length=2, verbose_name='Reservation Status')),
                ('rating', models.FloatField(default=0, verbose_name='Rating')),
                ('canceled_reason', models.TextField(blank=True, null=True, verbose_name='Canceled Reason')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservations', to='Event.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
