###
@authToken =

###
# @name LogIn
POST http://127.0.0.1:8000/api/log-in/
Content-Type: application/json
Accept-Language: en

{
    "email": "s@s.com",
    "password": "shady123456789"
}

> {%
    client.global.set("authToken", response.body.token);
%}

###
# curl -X GET http://127.0.0.1:8000/api/user/my-interests/ -H 'Authorization: Token e1e9a29bb197299157f210169cee2b800622de9f'

###
# @name GetAllUserInterests
GET http://127.0.0.1:8000/api/user/my-interests/
Authorization: Token e1e9a29bb197299157f210169cee2b800622de9f

###
# @name GetOneUserInterest
GET http://127.0.0.1:8000/api/user/my-interests/5
Authorization: Token e1e9a29bb197299157f210169cee2b800622de9f

###
# @name AddToUserInterests
POST http://127.0.0.1:8000/api/user/my-interests/
Content-Type: application/json
Accept: application/json
Accept-Language: en
Authorization: Token e1e9a29bb197299157f210169cee2b800622de9f

{
  "category": "http://127.0.0.1:8000/api/categories/2/",
  "order": 1
}
###
# @name UpdateUserInterest
PUT http://127.0.0.1:8000/api/user/my-interests/6/
Content-Type: application/json
Accept: application/json
Accept-Language: en
Authorization: Token e1e9a29bb197299157f210169cee2b800622de9f

{
  "category": "http://127.0.0.1:8000/api/categories/6/",
  "order": 1
}
###
# @name DeleteUserInterest
DELETE http://127.0.0.1:8000/api/user/my-interests/6/
Content-Type: application/json
Accept: application/json
Accept-Language: en
Authorization: Token e1e9a29bb197299157f210169cee2b800622de9f


###
GET {{$dotenv apiBaseUrl}}/api/user/my-interests/
Content-Type: application/json
Accept: application/json
Accept-Language: en
Authorization: Token {{authToken}}


